const FETCH_MONSTERS_REQUEST = 'FETCH_MONSTERS_REQUEST';
const FETCH_MONSTERS_SUCCESS = 'FETCH_MONSTERS_SUCCESS';
const FETCH_MONSTERS_FAILURE = 'FETCH_MONSTERS_FAILURE';
const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  FETCH_MONSTERS_FAILURE, FETCH_MONSTERS_REQUEST, FETCH_MONSTERS_SUCCESS,
  CHANGE_FILTER,
};
